# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'



trigger:
  branches:
    include:
    - master

pool:
  vmImage: "ubuntu-latest"

steps:
#- checkout: none
- checkout: self
  persistCredentials: true
  clean: true
   
- script: |
    echo $(Build.SourceBranch)
    echo $(Build.SourceBranchName)
    echo $(Build.SourceVersion)
    echo $(Build.SourceVersionMessage)
    echo $(Build.Repository.Uri)
    echo $(Build.Repository.Name)
    echo $(Build.QueuedBy)
    echo $(Build.DefinitionName)
- task: Maven@3
  inputs:
    mavenPomFile: '$(Build.SourceVersionMessage)/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    goals: 'package'

- task: CmdLine@2
  inputs:
    script:
      cd $(Pipeline.Workspace)/s/  | 
      jar cf jar-file.jar $(Build.SourceVersionMessage)/src/main/java/com/uga/*
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)/s/jar-file.jar'
    artifactType: 'pipeline'
    artifactName: 'jar-file'
